create table if not exists public.chatbot2_users (
    id text primary key,
    channel_id text not null,
    user_id text not null,
    display_nickname text not null default '',
    points bigint not null default 0,
    attendance_days integer not null default 0,
    attendance_streak integer not null default 0,
    last_attendance_date text,
    total_chat_count bigint not null default 0,
    game_enabled boolean not null default true,
    updown_wins integer not null default 0,
    choseong_wins integer not null default 0,
    last_chat_at timestamptz,
    last_join_at timestamptz,
    last_leave_at timestamptz,
    last_seen_at timestamptz not null default now(),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists idx_chatbot2_users_channel_id on public.chatbot2_users(channel_id);
create index if not exists idx_chatbot2_users_user_id on public.chatbot2_users(user_id);
create index if not exists idx_chatbot2_users_points on public.chatbot2_users(channel_id, points desc);

create table if not exists public.chatbot2_chat_logs (
    id bigint generated by default as identity primary key,
    channel_id text not null,
    user_id text not null,
    nickname text not null default '',
    message text not null default '',
    created_at timestamptz not null default now()
);

create index if not exists idx_chatbot2_chat_logs_channel_created_at on public.chatbot2_chat_logs(channel_id, created_at desc);
create index if not exists idx_chatbot2_chat_logs_user_created_at on public.chatbot2_chat_logs(user_id, created_at desc);

create table if not exists public.chatbot2_shop_items (
    id text primary key,
    channel_id text not null,
    item_key text not null,
    name text not null,
    price integer not null default 0,
    description text not null default '',
    is_active boolean not null default true,
    created_by text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists idx_chatbot2_shop_items_channel_id on public.chatbot2_shop_items(channel_id);
create unique index if not exists idx_chatbot2_shop_items_channel_item_key on public.chatbot2_shop_items(channel_id, item_key);
